name: Lint Markdown
on: [pull_request]
jobs:
  TruffleHog:
    runs-on: ubuntu-latest
      - name: markdownlint-cli
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: nosborn/github-action-markdown-cli@v3.0.1
        with:
          files: .
